### ISSUE TITLE
Indicate JSON errors in the input data

### ISSUE THREAD

**Issue by christian-konrad** [camunda/form-playground#20]
__Is your feature request related to a problem? Please describe.__

When the form mock input data is invalid, the form rendering stops, but there is no indicator of that error. Users might think the error is in the form, rather than in the input json.

__Describe the solution you'd like__

We should indicate it in the problems panel, as well as highlight the error in the json panel.

__Describe alternatives you've considered__

Show an error in the form preview itself, since users may spend their attention into this window. But this may result in too much flickering of the preview window.

__Additional context__

**Comment by pinussilvestrus** [comment]
One simple thing we can do is use the linting capabilities of the [`lang-json`](https://github.com/codemirror/lang-json) CodeMirror package.

![image](https://user-images.githubusercontent.com/9433996/199974098-ea39670e-fd64-4585-8763-293516c7e43b.png)

> We should indicate it in the problems panel

That's anyway something that would need to be fixed in the Desktop Modeler directly. What can help here is to fire an event once a parsing error happens.

```js
formPlayground.on('formPlayground.inputDataError', function(error) {
  // do stuff, e.g. display in problems panel
});
```

**Comment by pinussilvestrus** [comment]
I sketched that via https://github.com/bpmn-io/form-js/pull/386
